const { COMPLAINT_STATUS } = require('../../constants/complaint-management/complaintStatusConstants');

/**
 * Validates if a status transition is allowed.
 * @param {string} currentStatus 
 * @param {string} nextStatus 
 * @returns {boolean}
 */
const isValidTransition = (currentStatus, nextStatus) => {
    const transitions = {
        [COMPLAINT_STATUS.SUBMITTED]: [COMPLAINT_STATUS.UNDER_REVIEW, COMPLAINT_STATUS.REJECTED, COMPLAINT_STATUS.CLOSED],
        [COMPLAINT_STATUS.UNDER_REVIEW]: [COMPLAINT_STATUS.ASSIGNED, COMPLAINT_STATUS.REJECTED, COMPLAINT_STATUS.WAITING_FOR_STUDENT],
        [COMPLAINT_STATUS.ASSIGNED]: [COMPLAINT_STATUS.IN_PROGRESS, COMPLAINT_STATUS.RESOLVED, COMPLAINT_STATUS.ESCALATED],
        [COMPLAINT_STATUS.IN_PROGRESS]: [COMPLAINT_STATUS.RESOLVED, COMPLAINT_STATUS.WAITING_FOR_STUDENT, COMPLAINT_STATUS.ESCALATED],
        [COMPLAINT_STATUS.WAITING_FOR_STUDENT]: [COMPLAINT_STATUS.IN_PROGRESS, COMPLAINT_STATUS.RESOLVED, COMPLAINT_STATUS.CLOSED],
        [COMPLAINT_STATUS.RESOLVED]: [COMPLAINT_STATUS.CLOSED, COMPLAINT_STATUS.REOPENED],
        [COMPLAINT_STATUS.REOPENED]: [COMPLAINT_STATUS.UNDER_REVIEW, COMPLAINT_STATUS.ASSIGNED, COMPLAINT_STATUS.ESCALATED],
        [COMPLAINT_STATUS.REJECTED]: [COMPLAINT_STATUS.CLOSED],
        [COMPLAINT_STATUS.ESCALATED]: [COMPLAINT_STATUS.IN_PROGRESS, COMPLAINT_STATUS.RESOLVED, COMPLAINT_STATUS.CLOSED]
    };

    return (transitions[currentStatus] || []).includes(nextStatus);
};

module.exports = isValidTransition;
